#include "IREquality.h"
#include "PVLPrinter.h"
#include "IROperator.h"
#include "Substitute.h"
#include "IRMutator.h"

using std::string;
using std::vector;

namespace Halide {
namespace Internal {

    class AddTrigger : public IRMutator {
    string func;
    vector<Expr> &def_args;
    vector<Expr> &pure_args;
    bool buffer_annotation;
public:
    bool trigger_added;

    AddTrigger(const string &func, vector<Expr> &def_args, vector<Expr> &pure_args, bool buffer_annotation)
        : def_args(def_args), pure_args(pure_args),  buffer_annotation(buffer_annotation), trigger_added(false) {
            // We remove any $ in the name of a buffer 
            if(buffer_annotation){
                size_t pos = func.find('$');
                if (pos != std::string::npos) {
                    this->func = func.substr(0, pos);
                } else {
                    this->func = func;
                }
            } else {
                this->func = func;
            }
        }
    using IRMutator::visit;
private:
    

    Expr visit(const Call *op) override {
        Expr res = IRMutator::visit(op);
        // We only care if we call our selves.
        string name = op->name;
        if(buffer_annotation){
            size_t pos = name.find('$');
            if (pos != std::string::npos) {
                name = name.substr(0, pos);
            }
            if(ends_with(name, "_im"))
                name.erase(name.length()-3);
        }
        if (name != func || op->call_type != Call::Halide) {
            return res;
        }
        if(op->args.size() != def_args.size()){
            internal_error << "Function " << func << " was called with " << op->args.size() << " arguments, but it has " << def_args.size() << " arguments";
        }
        for(size_t i = 0; i < op->args.size(); i++){
            if(!equal(op->args[i], def_args[i]) && !equal(op->args[i], pure_args[i])){
                user_error << "Function must be called with the same arguments as the definition, but it was called with different arguments: " << op->args[i] << " != " << def_args[i];
            }
        }
        
        if(trigger_added) return res;
        // If we call our self with the same arguments, we add a trigger
        trigger_added = true;
        return trigger(res);
    }
};

Expr add_trigger(Expr e, const string &func, vector<Expr> &def_args, vector<Expr> &pure_args, bool buffer_annotation) {
    AddTrigger at(func, def_args, pure_args, buffer_annotation);
    Expr res = at.mutate(e);
    if(!at.trigger_added){
        string what = buffer_annotation ? "buffer" : "function";
        user_error << "Each annotation of " << func << " must call that " << what << ", but it was not called in the annotation: " << e;
        // If we added a trigger, we return the new expression
        return res;
    }

    return res;
}

const string pvl_header = R"INLINE_CODE(
/* MACHINE GENERATED By Halide. */

 decreases;
pure int max(int x, int y) = x > y ? x : y;
 
 decreases;
pure int min(int x, int y) = x > y ? y : x;
 
 decreases;
pure rational max(rational x, rational y) = x > y ? x : y;
 
 decreases;
pure rational min(rational x, rational y) = x > y ? y : x;
 
 decreases;
pure int abs(int x) = x >= 0 ? x : -x;

 decreases;
pure rational abs(rational x) = x >= 0 ? x : -x;
 
 decreases;
pure rational ceil_f32(rational x) = is_int(x) ? x : int_to_rational(rational_to_int(x) + 1);

prover_function int rational_to_int(rational r) \smtlib `(_ to_int)`;

prover_function int int_to_rational(int i) \smtlib `(_ to_real)`;
 
prover_function bool is_int(rational r) \smtlib `(_ is_int)`;
 
prover_function rational div_rat_(rational l, rational r) \smtlib `(_ /)`;
 
prover_function rational pow_f32(rational l, rational r) \smtlib `(_ ^)`;
 
 decreases;
pure rational div_rat(rational l, rational r) = div_rat_(l, r);
 
 decreases;
pure rational fast_inverse_f32(rational x) = div_rat(1.0f, x);
 
 decreases;
pure int round_f32(rational x) = is_int(x) ? rational_to_int(x) : rational_to_int(x + 0.5f);

 decreases;
pure int hdiv(int a, int b) = b==0 ? 0 : a/b;

 decreases;
pure int hmod(int a, int b) = b==0 ? 0 : a%b;

)INLINE_CODE";

string c_print_name_pvl(const string &name){
    string res = c_print_name(name);
    internal_assert(res.size() > 1 );
    if(res[0] == '_') res = res.substr(1);
    if(!isalpha(res[0])) res = "x" + res;
    return res;
}

PVLPrinter::PVLPrinter(std::ostream &s) : IRPrinter(s), in_annotations(false), in_reduction(false), buffer_annotation(false) {
    s << pvl_header;
}

void PVLPrinter::visit(const Call *op) {
    string name = op->name;
    vector<Expr> args = op->args;

    if(name == func_name){
        if(in_annotations){
            user_assert(call_correct(op)) << "The call '" << (const Expr) op << "' is not called correctly in the annotations of " << func_name;
            stream << "\\result";
            return;
        }

        name = prev_def_name;
        // The reduction function needs extra arguments (rx-1, ry-1, ...)
        if(in_reduction){
            stream << c_print_name_pvl(name) << "(";
            print_list(args);
            if(!args.empty() && !rvars.empty()) stream << ", ";
            for(size_t i=0; i<rvars.size(); i++){
                //We want the -1 only for the first rvar
                stream << c_print_name_pvl(rvars[i]);
                if(i==0) stream << " - 1";
                if(i<rvars.size()-1) stream << ", ";
            }
            stream <<")";
            return;
        }
    }
    if(op->is_intrinsic(Call::trigger)) {
        internal_assert(op->args.size() == 1);
        stream << "{:";
        print(op->args[0]);
        stream << ":}";
        return;
    } else if(op->is_intrinsic(Call::mux)) {
        internal_assert(op->args.size() > 1);

        for(size_t i = 1; i<op->args.size()-1; i++){
            print(args[0]);
            stream << " == " << (i-1) << " ? ";
            print(args[i]);
            stream << " : ";
        }
        print(args[op->args.size()-1]);
        return;
    } else if(op->is_intrinsic(Call::likely) || op->is_intrinsic(Call::likely_if_innermost)) {
        internal_assert(op->args.size() == 1);
        print(op->args[0]);
        return;
    }

    if(op->is_extern()){
        stream << name;
    } else {
        stream << c_print_name_pvl(name);
    }
    
    stream << "(";
    print_list(args);
    stream << ")";
}

void PVLPrinter::visit(const Let *op){
    print(substitute(op->name, op->value, op->body));
}

void PVLPrinter::visit(const Forall *op){
    stream << "(\\forall";
    for(size_t i= 0; i<op->vars.size(); i++){
        stream << " int " << c_print_name_pvl(op->vars[i]);
        if (i < op->vars.size() - 1) {
            stream << ", ";
        }
    }
    

    stream << "; ";

    print_no_parens(op->select);
    stream << "; ";
    print_no_parens(op->main);
    stream << ")";
}

void PVLPrinter::visit(const Exists *op) {
    stream << "(\\exists";
    for(size_t i= 0; i<op->vars.size(); i++){
        stream << " int " << c_print_name_pvl(op->vars[i]);
        if (i < op->vars.size() - 1) {
            stream << ", ";
        }
    }

    print_no_parens(op->select);
    stream << "; ";
    print_no_parens(op->main);
    stream << ")";
}

bool PVLPrinter::ends_on_dimension(string name){
    vector<string> split = split_string(name, ".");
    if(split.size() < 3) return false;
    int dim;
    try {
        dim = std::stoi(split.back());
        if(dim<0) return false;
    } catch (...) {
        return false;
    }
    
    string begin;
    for(size_t i = 0; i < split.size()-2; i++){
        begin = begin + c_print_name_pvl(split[i]);
        begin = begin + "_";
    }

    string extent_s = begin + "extent_" + std::to_string(dim) + "()";
    string min_s = begin + "min_" + std::to_string(dim) + "()";
    string stride_s = begin + "min_" + std::to_string(dim) + "()";

    if(split[split.size()-2] == "max"){
        stream << "(";
        auto it = parameter_map.find(split[0]);
        if(split.size() == 3 && it != parameter_map.end() && it->second.dimensions() > dim 
            && it->second.min_constraint(dim).defined()){                
            print(it->second.min_constraint(dim));
        } else {
            stream << min_s;
        }
        stream << " + ";
        if(split.size() == 3 && it != parameter_map.end() && it->second.dimensions() > dim 
            && it->second.extent_constraint(dim).defined()){                
            print(it->second.extent_constraint(dim));
        } else {
            stream << extent_s;
        }
        stream << ")";
    } else if(split[split.size()-2] == "min"){
        auto it = parameter_map.find(split[0]);
        if(split.size() == 3 && it != parameter_map.end() && it->second.dimensions() > dim 
            && it->second.min_constraint(dim).defined()){                
            print(it->second.min_constraint(dim));
        } else {
            stream << min_s;
        }
    } else if(split[split.size()-2] == "extent") {
        auto it = parameter_map.find(split[0]);
        if(split.size() == 3 && it != parameter_map.end() && it->second.dimensions() > dim 
            && it->second.extent_constraint(dim).defined()){                
            print(it->second.extent_constraint(dim));
        } else {
            stream << extent_s;
        }
    } else if(split[split.size()-2] == "stride") {
        auto it = parameter_map.find(split[0]);
        if(split.size() == 3 && it != parameter_map.end() && it->second.dimensions() > dim 
            && it->second.stride_constraint(dim).defined()){                
            print(it->second.stride_constraint(dim));
        } else {
            stream << stride_s;
        }
    } else {
        return false;
    }

    return true;
}

void PVLPrinter::visit(const Variable *op) {
    if((op->reduction_domain.defined() || reduction_vars.contains(op->name)) && !in_annotations){
        // Reduction domains variable in definitions should be called with -1
        stream << "(" << c_print_name_pvl(op->name) << " - 1)";
    } else if(ends_on_dimension(op->name)) {
        // Already printed in ends_on_dimension
        return;
    } else {
        stream << c_print_name_pvl(op->name);
    }
}

void PVLPrinter::visit(const UIntImm *op) {
    if(op->type.bits() == 1){
        if(op->value == 1){
            stream << "true";
        } else {
            stream << "false";
        }
    } else {
        stream << std::to_string(op->value);
    }
}

void PVLPrinter::visit(const Select * op) {
        stream << "(";
        print(op->condition);
        stream << " ? ";
        print(op->true_value);
        stream << " : ";
        print(op->false_value);
        stream << ")";
}

void PVLPrinter::visit(const AnnExpr *op) {
    switch(op->ann_type) {
        case AnnotationType::Require:
            if(buffer_annotation){
                // user_error << "Require annotation is only allowed for image parameters: " << op << "\n";
                stream << "ensures ";
            } else {
                stream << "requires ";
            }
        break;
    case AnnotationType::LoopInvariant:
        user_error << "Incorrect annotation type: " << (const Annotation) op << "\n";
        break;
    case AnnotationType::Ensure:
        stream << "ensures ";
        break;
    case AnnotationType::Context:
        stream << "context ";
        break;
    case AnnotationType::ContextEverywhere:
        stream << "context_everywhere ";
        break;
    }

    print_no_parens(op->condition);
}

bool PVLPrinter::call_correct(const Call *op) {
    // Check the arguments
    if(op->args.size() != pure_args.size()) return false;

    for (size_t i = 0; i < op->args.size(); i++) {
        // Either they are equal to the def args, or same as the original variable
        if(!equal(op->args[i], def_args[i]) && !(op->args[i].as<Variable>() != nullptr && op->args[i].as<Variable>()->name == pure_args[i]))
            return false;
    }

    return true;
}

void PVLPrinter::visit(const Cast *op){
    Expr e = op->value;
    Type t = op->type;
    if(e.type().is_float() && t.is_int_or_uint()){
        stream << "rational_to_int(";
        print(e);
        stream << ")";
    } else if(e.type().is_int_or_uint() && t.is_float()){
        stream << "int_to_rational(";
        print(e);
        stream << ")"; 
    } else if(e.type().is_int_or_uint() && t.is_int_or_uint()){
        print(e);
    } else {
        internal_error << "Not supported cast by pvl";
    }
}

void PVLPrinter::visit(const Div *op){
    Expr a = op->a;
    Expr b = op->b;
    if(a.type().is_float() && b.type().is_float() ){
        stream << "div_rat(";
        print(a);
        stream << ", ";
        print(b);
        stream << ")";
    } else if(a.type().is_int_or_uint() && b.type().is_int_or_uint() ){
        stream << "hdiv(";
        print(a);
        stream << ", ";
        print(b);
        stream << ")";
    } else {
        internal_error << "Not supported div by pvl";
    }
}

void PVLPrinter::visit(const Mod *op){
    Expr a = op->a;
    Expr b = op->b;
    if(a.type().is_int_or_uint() && b.type().is_int_or_uint() ){
        stream << "hmod(";
        print(a);
        stream << ", ";
        print(b);
        stream << ")";
    } else {
        internal_error << "Not supported mod by pvl";
    }
}

void PVLPrinter::print_pipeline(const vector<Annotation> &anns){
    func_name =  "";
    prev_def_name = "";
    pure_args = {};
    def_args = {};
    
    in_annotations = true;
    print_ann(anns);
    in_annotations = false;

    stream << "void pipeline(){ }\n";
    
}

void PVLPrinter::print_func(Function f){
    func_name =  f.name();
    prev_def_name = "";
    pure_args = f.args();
    def_args = f.definition().args();

    string new_name = f.updates().size() == 0 ? func_name : func_name + "0";

    in_annotations = true;
    print_ann(f.definition().annotations());
    in_annotations = false;
    print_def(f.definition(), f.args(), f.output_types(), new_name, "");

    stream << "\n";
    
    int nr = 1;
    for(const auto &update : f.updates()){
        prev_def_name = new_name;
        def_args = update.args();
        new_name = (int)f.updates().size() == nr ? func_name : func_name + std::to_string(nr);
        nr++;

        in_annotations = true;
        print_ann(update.annotations(), !update.schedule().rvars().empty());
        in_annotations = false;
        print_def(update, f.args(), f.output_types(), new_name, prev_def_name);

        stream << "\n";
    }

    // stream << ");\n \n";
}

void PVLPrinter::print_buffer_members(Parameter p){
    parameter_map[p.name()] = p;

    for(int i = 0; i < p.dimensions(); i++){
        stream << " decreases;\n";
        stream << "pure int " << c_print_name_pvl(p.name()) << "_min_" << i << "()";
        if(p.min_constraint(i).defined()){
            stream << " = ";
            print(p.min_constraint(i));
        }
        stream << ";\n";
    }

    for(int i = 0; i < p.dimensions(); i++){
        stream << " decreases;\n";
        stream << "pure int " << c_print_name_pvl(p.name()) << "_extent_" << i << "()";
        if(p.extent_constraint(i).defined()){
            stream << " = ";
            print(p.extent_constraint(i));
        }
        stream << ";\n";
    }

    for(int i = 0; i < p.dimensions(); i++){
        stream << " decreases;\n";
        stream << "pure int " << c_print_name_pvl(p.name()) << "_stride_" << i << "()";
        if(p.stride_constraint(i).defined()){
            stream << " = ";
            print(p.stride_constraint(i));
        }
        stream << ";\n";
    }
    stream << "\n";
}

void PVLPrinter::print_buffer(Parameter p, bool is_input){
    print_buffer_members(p);

    vector<string> implicit_args;
    vector<Expr> implicit_vars;
    for(int i=0; i < p.dimensions(); i++){
        string implicit = "_" + to_string(i);
        implicit_args.emplace_back(implicit);
        implicit_vars.emplace_back(Variable::make(Int(32), implicit));
    }

    func_name = p.name() + "_im";
    prev_def_name = p.name();
    pure_args = implicit_args;
    def_args = implicit_vars;

    if(!is_input){
        // user_assert(p.annotations().empty()) << "Output buffer " << p.name() << " should not have annotations";
        return;
    }

    in_annotations = true;
    buffer_annotation = true;
    print_ann(p.annotations());
    buffer_annotation = false;
    in_annotations = false;

    stream << " decreases;\n";
    print_lhs_def(implicit_args, {p.type()}, p.name());
    stream << ";\n\n";
}

void PVLPrinter::print_ann(const vector<Annotation> &anns, bool has_reduction){
    indent++;
    for(const auto &ann: anns){
        // Do not error on loop invariants for reductions
        if(has_reduction && ann.type() == AnnotationType::LoopInvariant) continue;
        stream << get_indent();
        print(ann);
        stream << ";\n";
    }
    indent--;
}

void PVLPrinter::print_reduction_ann(const vector<Annotation> &anns, const vector<ReductionVariable> &red_vars){
    indent++;

    for(const auto &r: red_vars){
        stream << get_indent() << "requires ";
        print(r.min);
        stream << " <= " << c_print_name_pvl(r.var) << " && " << c_print_name_pvl(r.var) << " <= ";
        print(r.min);
        stream << " + ";
        print(r.extent);
        stream << ";\n";
    }


    for(const auto &ann: anns){
        // Do not error on loop invariants for reductions
        if(ann.type() != AnnotationType::LoopInvariant) continue;
        internal_assert(ann.as<AnnExpr>() != nullptr) << "Only expression annotations allowed here";
        stream << get_indent() << "ensures ";
        print(ann.as<AnnExpr>()->condition);
        stream << ";\n";
    }
    indent--;
}

void PVLPrinter::print_def(Definition def, vector<string> original_args, vector<Type> output_types, string func_name, string old_func_name){

    stream << get_indent() << " " << "decreases;\n";
    print_lhs_def(original_args, output_types, func_name);
    stream << " = ";

    // Check if this update definition has different arguments than the pure definition
    vector<Expr> different_args;
    for(size_t i = 0; i< def.args().size(); i++) {
        // If we do not have the original variable, we need to add an equality
        if(!(def.args()[i].as<Variable>() != nullptr && def.args()[i].as<Variable>()->name == original_args[i])){
            different_args.emplace_back(EQ::make(Variable::make(Int(32), original_args[i]), def.args()[i]));
        }
    }

    // Check for reduction variables
    if(!def.schedule().rvars().empty()){
        // Go make the reduction function here
        return print_red_func(def, original_args, different_args, output_types, func_name, old_func_name);
    }

    if(!different_args.empty()){
        for(size_t i = 0; i < different_args.size(); i++) {
            print(different_args[i]);
            if (i + 1 < different_args.size()) {
                stream << " && ";
            }
        }

        stream << " ? ";
    }
    
    if(def.values().size() == 1){
        print_no_parens(def.values()[0]);
    } else {
        stream << "(";
        for (size_t i = 0; i < def.values().size(); i++) {
            print_no_parens(def.values()[i]);
            if (i + 1 < def.values().size()) {
                stream << ", ";
            }
        }
        stream << ")";
    }

    if(!different_args.empty()){
        stream << " : " << c_print_name_pvl(old_func_name) << "(";

        for (size_t i = 0; i < original_args.size(); i++) {
            stream << c_print_name_pvl(original_args[i]);
            if (i + 1 < original_args.size()) {
                stream << ", ";
            }
        }
        stream << ")";
    }
    stream << ";\n";
}

void PVLPrinter::print_lhs_def(vector<string> original_args, vector<Type> output_types, string func_name){
    stream << get_indent() << "pure ";

    if(output_types.size() == 1){
        print_type(output_types[0]);
        stream << " ";
    } else {
        stream << "(";
        for (size_t i = 0; i < output_types.size(); i++) {
            print_type(output_types[i]);
            if (i + 1 < output_types.size()) {
                stream << ", ";
            }
        }
        stream << ")";
    }
    
    stream << c_print_name_pvl(func_name) << "(";

    for (size_t i = 0; i < original_args.size(); i++) {
        stream << "int " << c_print_name_pvl(original_args[i]);
        if (i + 1 < original_args.size()) {
            stream << ", ";
        }
    }

    stream << ")";
}

void PVLPrinter::print_red_func(Definition def, vector<string> original_args, vector<Expr> different_args, vector<Type> output_types,
        string func_name, string old_func_name){
    // We are going to make a new function, that is going to loop through our reduction variables
    // So we call that function and define it afterwards.
    string reduction_func = func_name + "r";
    prev_def_name = reduction_func;
    stream << c_print_name_pvl(reduction_func) << "(";
    for (size_t i = 0; i < original_args.size(); i++) {
        stream << c_print_name_pvl(original_args[i]) << ", ";
    }

    vector<ReductionVariable> red_vars = def.schedule().rvars();
    rvars.clear();
    vector<string> new_args = original_args;
    for (size_t i = 0; i < red_vars.size(); i++) {
        print(red_vars[i].min);
        if(i + 1 == red_vars.size()){
            stream << " + ";
            print(red_vars[i].extent);
        } else {
            stream << ", ";
        }
        
        new_args.emplace_back(red_vars[i].var);
        reduction_vars.push(red_vars[i].var);
        rvars.emplace_back(red_vars[i].var);
    }

    stream << ");\n\n";
    // We have now printed the outer function call


    in_annotations = true;
    print_reduction_ann(def.annotations(), red_vars);
    in_annotations = false;
    indent++;
    stream << get_indent() << "decreases ";
    for (int i = (int) red_vars.size()-1; i >=0; i--) {
        stream << c_print_name_pvl(red_vars[i].var);
        if(i != 0) stream << ", ";
    }
    stream << ";\n";
    indent--;
    print_lhs_def(new_args, output_types, reduction_func);
    // We printed the annotations and type signature, now we need to define the function

    stream << " = ";
    // First the part where all the reduction variables are at the minimum
    for (size_t i = 0; i < red_vars.size(); i++) {
        stream << c_print_name_pvl(red_vars[i].var) << " == ";
        print(red_vars[i].min);
        if (i + 1 < red_vars.size()) {
            stream << " && ";
        }
    }
    // First choice is the base function (old function)
    stream << " ? " << c_print_name_pvl(old_func_name) << "(";
    for (size_t i = 0; i < original_args.size(); i++) {
        stream << c_print_name_pvl(original_args[i]);
        if (i + 1 < original_args.size()) {
            stream << ", ";
        }
    }
    stream << ") : ";

    // We go from the last rvar to the first
    for(int i = (int)red_vars.size()-1; i>0; i--){
        // The vars r_0, r_1, ..., r_{i-1} are zero (and r_i is not zero)
        for(int j = 0; j<i; j++){
            stream << c_print_name_pvl(red_vars[j].var) << " == ";
            print(red_vars[j].min);
            if (j + 1 < i) {
                stream << " && ";
            }
        }

        stream << " ? " << c_print_name_pvl(reduction_func) << "(";
        // Print normal arguments
        for (int k = 0; k < (int)original_args.size(); k++)
            stream << c_print_name_pvl(original_args[k]) << ", ";
        // Reset variables r_0 to r_{i-2} to minimum
        // and variables r_{i-1} to the maximum 
        for(int j = 0; j<i; j++){
            print(red_vars[j].min);
            if(j+1 == i){
                stream << " + ";
                print(red_vars[j].extent);
            }
            stream << ", ";
        }
        

        // Substract one from r_i
        stream << c_print_name_pvl(red_vars[i].var) << " - 1";
        // The remaining reduction variables are placed as is
        for(int k=i+1; k<(int)red_vars.size(); k++)
            stream << ", " << c_print_name_pvl(red_vars[k].var);
        // Close function call
        stream << ") : ";
    }
    // If there are different arguments or a predicate we only go conditionally to the actual definition
    if(!different_args.empty() || def.predicate().defined()){
        Expr condition;
        for(size_t i = 0; i < different_args.size(); i++) {
            condition = i == 0 ? different_args[i] : (condition && different_args[i]);
        }
        if(def.predicate().defined()){
            condition = condition.defined() ? (condition && def.predicate()) : def.predicate();
        }
        print_no_parens(condition);

        stream << " ? ";
    }

    in_reduction = true;

    if(def.values().size() == 1){
        print_no_parens(def.values()[0]);
    } else {
        // TODO: Consider if this is correct, if there are function with reduction variables and multiple values
        stream << "(";
        for (size_t i = 0; i < def.values().size(); i++) {
            print_no_parens(def.values()[i]);
            if (i + 1 < def.values().size()) {
                stream << ", ";
            }
        }
        stream << ")";
    }

    in_reduction = false;

    if(!different_args.empty() || def.predicate().defined()){
        stream << " : " << c_print_name_pvl(reduction_func) << "(";

        for (size_t i = 0; i < original_args.size(); i++) {
            stream << c_print_name_pvl(original_args[i]) << ", ";
        }
        for (size_t i = 0; i < red_vars.size(); i++) {
            stream << c_print_name_pvl(red_vars[i].var);
            // Only the first one gets reduced
            if(i==0) stream << " - 1";
            if (i + 1 < red_vars.size()) {
                stream << ", ";
            }
        }
        stream << ")";
    }
    stream << ";\n";

    for (size_t i = 0; i < red_vars.size(); i++) {
        reduction_vars.pop(red_vars[i].var);
    }
}

void PVLPrinter::print_type(const Type &type) {
    switch (type.code()) {
    case Type::Int:
        stream << "int";
        break;
    case Type::UInt:
        stream << "int";
        break;
    case Type::Float:
        stream << "rational";
        break;
    default:
        user_error << "Unsupported type " << type << " for PVL translation";
}
}

}
}